apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-restart
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-restart
  template:
    metadata:
      labels:
        app: test-restart
    spec:
      containers:
      - name: test-container
        image: busybox
        command: ["/bin/sh", "-c", "sleep 10; exit 1"]