name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push All Service Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          services=$(ls src)
          for service in $services; do
            DOCKERFILE=src/$service/Dockerfile
            if [ -f "$DOCKERFILE" ]; then
              echo "🔨 Building $service"
              docker build \
                -f $DOCKERFILE \
                -t $ECR_REGISTRY/$ECR_REPOSITORY:$service-$IMAGE_TAG \
                .
              echo "🚀 Pushing $service"
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$service-$IMAGE_TAG
            else
              echo "⚠️ Skipping $service (No Dockerfile)"
            fi
          done